### ISSUE TITLE
Unable to install Canvas UI

### ISSUE THREAD

**Issue by nsaliu** [austintoddj/canvas#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Admin**
I cleaned and new Laravel 11 installation.  
I executed these commands:
- `composer require austintoddj/canvas`
- `php artisan canvas:install`
- `php artisan storage:link`

And everything is fine - I can access the admin section and create posts.

**UI**
I executed these commands:
- `php artisan canvas:ui`
- `npm install`

when executing `npm run canvas.ui.dev` I'm receiving this error:

```shell
www-data@59b7af186f0b:~/html$ npm run canvas.ui.dev

> canvas.ui.dev
> mix

[webpack-cli] Error [ERR_REQUIRE_ESM]: require() of ES Module /var/www/html/webpack.mix.js from /var/www/html/node_modules/laravel-mix/setup/webpack.config.js not supported.
webpack.mix.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename webpack.mix.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /var/www/html/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at module.exports (/var/www/html/node_modules/laravel-mix/setup/webpack.config.js:11:5)
    at loadConfigByPath (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:1439:37)
    at async Promise.all (index 0)
    at async WebpackCLI.loadConfig (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:1454:35)
    at async WebpackCLI.createCompiler (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:1785:22)
    at async WebpackCLI.runWebpack (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:1890:20)
    at async Command.<anonymous> (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:912:21)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/var/www/html/node_modules/webpack-cli/lib/webpack-cli.js:1372:13) {
  code: 'ERR_REQUIRE_ESM'
}
```

Do you have any suggestions?  
Thanks!

### Environment

```markdown
- php version: 8.3.8
- npm: 10.9.0
- node: v18.20.4
- vite: vite/5.4.10 linux-arm64 node-v18.20.4
```

**Comment by ravenshill** [comment]
I am having the same issue, same sequence of commands

**Comment by nsaliu** [comment]
Any news here?

**Comment by pocketnest-erik** [comment]
Same issue.

**Comment by nsaliu** [comment]
I have the same config with `vite` and `vite --production` but as you can see in my previous comment unfortunately both `dev` and `prod` are not working.

**Comment by D0nVitalio** [comment]
> I have the same config with `vite` and `vite --production` but as you can see in my previous comment unfortunately both `dev` and `prod` are not working.

I found
https://github.com/EstebanBetancur1/Laravel-10-mix.git
and with
composer require austintoddj/canvas:6.0.46  (last version with webpack)
then standard commands
it works bundles, but, when go to http://127.0.0.1:8000/canvas-ui
shows error not found css and js files (resources\views\canvas-ui.blade.php)
I edited css an js to:
<link rel="stylesheet" type="text/css" href="{{ mix('css/app.css') }}">
<script type="text/javascript" src="{{ mix('js/app.js') }}"></script>

But got blank, white page. These js and css not giving 404.. Do you have idea?

**Comment by D0nVitalio** [comment]
@nsaliu 
Laravel 8 with composer require austintoddj/canvas:6.0.46
bundles with a lot warnings... but it works! http://127.0.0.1:8000/canvas-ui opens
If you will be able to run canvas on L10,L11 let us know

**Comment by austintoddj** [comment]
Closing as complete. Check out [v7.0](https://github.com/austintoddj/canvas/releases/tag/v7.0.0) for more.
