### ISSUE TITLE
Cannot upload files or create folders

### ISSUE THREAD

**Issue by cconover** [austintoddj/canvas#192]
When I attempt to upload a file, or create a new folder within the media interface, the file does not appear, and I get a strange gray box at the top right of the screen for about 5-10 seconds:

<img width="1313" alt="screen shot 2016-09-29 at 9 28 35 am" src="https://cloud.githubusercontent.com/assets/698158/18956268/d682b50a-8628-11e6-818b-e200b5bf7ba3.png">

This happens both when editing a post, as well as when inside the main media interface.

I have noticed that when I attempt to upload a file, a directory named `undefined` is created inside of `/public/storage` and the file is inside that new directory. However, it never appears in the web UI.

Here is the output of the system information:

```
### Begin System Info ###

## Please include this information when requesting technical support ##

SITE_URL:                   www.christiaanconover.com
SITE_IP:                    100.16.90.229
SITE_TIMEZONE:              America/New_York

PHP_VERSION:                7.0.8-0ubuntu0.16.04.2
PHP_MEMORY_LIMIT:           128M
PHP_TIME_LIMIT:             30

DATABASE_CONNECTION:        MYSQL

WEB_SERVER:                 nginx

LAST_INDEX_RUN:             2016-09-29 09:27:49

### End System Info ###
```

**Comment by austintoddj** [comment]
@talvbansal Any thoughts on this?

**Comment by talvbansal** [comment]
Hi @cconover is there anything within the /storage/logs/laravel.log file?

**Comment by cconover** [comment]
This is the latest entry in the log:

```
[2016-09-29 02:28:13] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in /srv/www/christiaanconover.com/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:293
Stack trace:
#0 /srv/www/christiaanconover.com/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(293): PDOStatement->execute()
#1 /srv/www/christiaanconover.com/app/Models/Post.php(171): TeamTNT\TNTSearch\Indexer\TNTIndexer->delete(1)
#2 [internal function]: App\Models\Post::deleteFromIndex(Object(App\Models\Post))
#3 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#4 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1665): Illuminate\Events\Dispatcher->fire('eloquent.delete...', Array)
#5 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1121): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.delete...', false)
#6 /srv/www/christiaanconover.com/app/Http/Controllers/Backend/PostController.php(100): Illuminate\Database\Eloquent\Model->delete()
#7 [internal function]: App\Http\Controllers\Backend\PostController->destroy('1')
#8 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#9 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('destroy', Array)
#10 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Backend\PostController), 'destroy')
#11 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#12 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(267): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /srv/www/christiaanconover.com/vendor/proengsoft/laravel-jsvalidation/src/RemoteValidationMiddleware.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Proengsoft\JsValidation\RemoteValidationMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /srv/www/christiaanconover.com/app/Http/Middleware/CheckForMaintenanceMode.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): App\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /srv/www/christiaanconover.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 /srv/www/christiaanconover.com/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 {main}
```

**Comment by talvbansal** [comment]
So that log output is to do with the sqlite databases that the tnt search indexer. Its an sqlite specific issue that means that the databases parent folder (in this case `/storage`) needs to have write permissions. However i don't think that this would have anything to do with the media manager

When you perform an upload is that all that comes up in the logs or is there anything else?

**Comment by cconover** [comment]
I just attempted another upload, and nothing was added to the log, but I'm getting the same behavior.

**Comment by austintoddj** [comment]
@cconover I've seen that error before. Step 6 of the installation asks you to do the following:

Run `chmod -R 777 storage/` to change the permissions of the `storage/` directory.

Can you try doing that and then running your test again?

**Comment by cconover** [comment]
I just did that, and I'm still seeing the same behavior.

**Comment by austintoddj** [comment]
Ok, just to verify, can you truncate the log and run it one more time to see the same stack trace error? 

@nticaric Looks like this might be a TNTSearch thing?

**Comment by talvbansal** [comment]
I don't mind taking a look this for you but without being able to repeat it I'd probably need access to your server?

**Comment by talvbansal** [comment]
@austintoddj that message in the logs is an Sqlite limitation, not specific to TntSearch its just that TntSearch uses an Sqlite database for its indexes.

To fix it the parent folder of the Sqlite folder must have write permissions.

**Comment by austintoddj** [comment]
That's what I thought, curious why he is still hitting that error then after he ran `chmod 777`

**Comment by cconover** [comment]
@austintoddj I just truncated the log, and nothing was added to it after attempting another upload.

**Comment by cconover** [comment]
Correct.

**Comment by talvbansal** [comment]
I'm happy to take a look on your server for you if you're comfortable with that however without being able to repeat the scenario I'm not sure how to take this forward.

**Comment by cconover** [comment]
@talvbansal I'm ok with that. I can set up an account for you. Let me know how best to get the details to you.

**Comment by talvbansal** [comment]
@cconover You can DM me on twitter @talv?

**Comment by austintoddj** [comment]
@cconover @talvbansal Let us know back here if you find a solution!

**Comment by cconover** [comment]
@talvbansal I'll DM you shortly.

**Comment by talvbansal** [comment]
This can be closed now, I can't close the issue myself otherwise I would have.
